### ISSUE TITLE
undefined method `values' for #<Array:0x007fb57548a4b8> in Wallet.all

### ISSUE THREAD

**Issue by Deekor** [mwerner/bittrex#3]
```
[6] pry(main)> Bittrex::Wallet.all
NoMethodError: undefined method `values' for #<Array:0x007fb57548a4b8>
```

Looks like the API response is an array of JSON object now.

**Comment by mlsaito** [comment]
Looks like this issue has already been fixed. Can we update the one hosted on rubygems.org too? Thanks!

**Comment by mwerner** [comment]
Done, thanks for the reminder @mlsaito 
https://rubygems.org/gems/bittrex/versions/0.0.2
